name: Maven - CI

on:
  workflow_dispatch:
  push:
    # Re-execute the CI on default branch only for status while ensuring it remains stable in any circumstances
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          # SonarQube - Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Testcontainers - Enable reusable containers
        run: echo 'testcontainers.reuse.enable=true' >> ~/.testcontainers.properties

      - name: Cache SonarCloud packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.sonar/cache
          key: sonar
          restore-keys: sonar

      - name: Maven build & SonarCloud quality scan
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar --activate-profiles ci --batch-mode --errors --strict-checksums --update-snapshots \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=djaytan \
            -Dsonar.projectKey=Djaytan_mc-jobs-reborn-patch-place-break
